name: pypi-release

on:
  push:
    tags:
      - "v*.*"

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python 3.9
        id: setup_python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Checkout Repo
        id: checkout_repo
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build Dist
        id: build_dist
        env:
          PKG_VER: ${{ github.ref }}
        run: |
          python3 -m pip install build --user
          python3 -m build
          ls -shl dist/

      - name: Publish to PyPI
        id: publish_pypi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
